[package]
name = "csv-rag"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
rig-core = { version = "0.9.0", features = ["derive"] }
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
